# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Edward's Home
tagline:          'swag'
description:      "Me: Who's smart in your class? Helen Dong: Me!"
url:              http://rn1n3r.github.com
baseurl:          /

author:
  name:           'Edward Ho'
  url:            /

paginate:         5

# Custom vars
version:          2.1.0

gems:
  - jemoji

excerpt_separator:
  -  <!--more-->
